services:
  - type: web
    name: blog-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: your_mongo_uri
      - key: JWT_SECRET
        value: your_jwt_secret

  - type: web
    name: blog-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
